### ISSUE TITLE
DisableMemDump 这个方法是不是笔误了

### ISSUE THREAD

**Issue by 857420437** [mosn/holmes#105]
// DisableMemDump disables the mem dump.
func (h *BHolmes) DisableMemDump() *BHolmes {
	h.opts.gCHeapOpts.Enable = false
	return h
}
是不是应该是
// DisableMemDump disables the mem dump.
func (h *BHolmes) DisableMemDump() *BHolmes {
	h.opts.memOpts.Enable = false
	return h
}

**Comment by taoyuanyuan** [comment]
老哥好眼力， 欢迎PR  👏🏻
