### ISSUE TITLE
report时传递更详细的现场信息

### ISSUE THREAD

**Issue by dumbFeng** [mosn/holmes#118]
鉴于线上告警场景的需求，如果能够将指标当前值、前n-1次采样的平均值以及指标相关的配置(min、max、abs、diff等)作为Report的参数传进来就好了。
目前参数中就只有reason能用，并且内容可读性不强。

**Comment by doujiang24** [comment]
听起来这个需求也合理的，有兴趣来贡献个 PR 不？

**Comment by LeslieRan** [comment]
> 听起来这个需求也合理的，有兴趣来贡献个 PR 不？

可以的，我来试试
