### ISSUE TITLE
输出的日志文件结构中的 previous和current代表内存吗？

### ISSUE THREAD

**Issue by sk872529557** [mosn/holmes#122]
输出的log文件中会打印出设置的配置和是否进行了dump,但是没看懂后面这两个代表什么意思，是内存吗？
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/45840584/190880307-c07bdb8e-f155-4f4e-b99f-26d3c617ad70.png">

**Comment by taoyuanyuan** [comment]
previous表示历史的统计值，current表示当前的统计值。这儿表示的就是mem的占比值。
