### ISSUE TITLE
get CPU core failed

### ISSUE THREAD

**Issue by istudies** [mosn/holmes#135]
Set `holmes.WithCGroup(true)` in the docker container. 
The log message indicates that the cpu core failed to be obtained.

```shell
2023-01-05 14:53:05,141 [INFO] [Holmes] use cgroup to limit memory
2023-01-05 14:53:05,143 [INFO] [Holmes] collect interval is resetting to [10s]
2023-01-05 14:53:15,144 [ERROR] [Holmes] get CPU core failed, CPU core: 0, error: <nil>
```

cgroup version: v1
```shell
root@master:/root# grep cgroup /proc/filesystems
nodev   cgroup
```

**Comment by istudies** [comment]
Should be caused by not adding the resource limit. After starting with the resource limit, it looks OK

docker-compose.yaml
```shell
    ...
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2g
   ...
```

**Comment by doujiang24** [comment]
@istudies Thanks for your reporting. Could you help to add a comment for this `WithCGroup` method? Thanks again.

**Comment by istudies** [comment]
@doujiang24 https://github.com/mosn/holmes/pull/136 PTAL
