### ISSUE TITLE
EnableDump: current cpu percent [1] greater than the CPUMaxPercent[90]

### ISSUE THREAD

**Issue by z760087139** [mosn/holmes#139]
I get "[INFO] [Holmes] unable to dump: current cpu percent [1] is greater than the CPUMaxPercent[90]"  in dump log

this is my holmes service coding like:
```go
        ctx, _ := context.WithTimeout(context.Background(), 10 * time.Hour)
	h, err := New(
		WithTextDump(),
		WithCollectInterval("5s"),
		WithCGroup(true),
		WithCPUDump(20,50,70,5*time.Minute),
		WithCPUMax(90),
		WithMemDump(20,50,70,5*time.Minute),
		WithGoroutineDump(6000, 50, 8000, 10 * 1000, 5*time.Minute),
		)
	if err != nil {
		return 
	}
	h = h.EnableCPUDump().EnableMemDump().EnableGoroutineDump()
	h.Start()
	go func(){
		<-ctx.Done()
		h.Stop()
	}()
```

**Comment by Jun10ng** [comment]
We fixed this issue on 08/22.  Here are [PR](https://github.com/mosn/holmes/commit/66a4f734ec3947511cb1889c996ce09f47869706)

Could you provide the holmes version in your application and check it?

**Comment by z760087139** [comment]
> We fixed this issue on 08/22. Here are [PR](https://github.com/mosn/holmes/commit/66a4f734ec3947511cb1889c996ce09f47869706), and we release it in [v1.2 tag](https://github.com/mosn/holmes/releases/tag/v1.0.2).
> 
> Could you provide the holmes version in your application and check it?

thx, im using holmes v1.1.0
