### ISSUE TITLE
"GOVCS disallows using bzr for public launchpad.net/gocheck" go get 提示错误

### ISSUE THREAD

**Issue by codjust** [mosn/holmes#146]
go version: go1.19.4 darwin/arm64
os: mac m2

1、操作：

> go get mosn.io/holmes
> go: mosn.io/holmes@v1.0.2 requires
> 	mosn.io/pkg@v0.0.0-20211217101631-d914102d1baf requires
> 	github.com/juju/testing@v0.0.0-20210324180055-18c50b0c2098 requires
> 	github.com/juju/utils/v2@v2.0.0-20200923005554-4646bfea2ef1 requires
> 	launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: unrecognized import path "launchpad.net/gocheck": GOVCS disallows using bzr for public launchpad.net/gocheck; see 'go help vcs'

2、看起来原因是：
导入了gocheck包，该包使用了bzr，但是go的vcs不支持了bzr版本控制工具了。

这个是不是需要升级下依赖库的依赖关系。

**Comment by codjust** [comment]
> 感谢提醒，最新的mosn/pkg已经没这个依赖的。是我们没有及时更新加上go vcs策略变更导致的。
> 
> ```
> grep "juju/testing" go.sum
> 
> // 当前holmes依赖的pkg commit
> git checkout d8b4e3d12cbb2d3852d3e7afc00347cc3042ec1 
> grep "juju/testing" go.sum
> ```
> 
> hi @doujiang24 为了避免这类问题再次发生，我们是否可以将pkg的版本指向release呢？会有什么风险吗。如果可以的话我提起一个pr

感谢及时回复，那是需要holmes更新go.mod对pkg的依赖版本，看下明天能不能提个pr先更新下，刚好这两天再尝试holmes项目，感谢。

**Comment by doujiang24** [comment]
> 感谢提醒，最新的mosn/pkg已经没这个依赖的。是我们没有及时更新加上go vcs策略变更导致的。
> 
> ```
> grep "juju/testing" go.sum
> 
> // 当前holmes依赖的pkg commit
> git checkout d8b4e3d12cbb2d3852d3e7afc00347cc3042ec1 
> grep "juju/testing" go.sum
> ```
> 
> hi @doujiang24 为了避免这类问题再次发生，我们是否可以将pkg的版本指向release呢？会有什么风险吗。如果可以的话我提起一个pr

@Jun10ng  可以的，欢迎 PR
