### ISSUE TITLE
support dynamic configuration

### ISSUE THREAD

**Issue by cch123** [mosn/holmes#2]

**Comment by marlonfan** [comment]
这块有什么规划么?  能想到的

- 基于http/rpc接口来暴露配置设置
- 基于apollo/nacos/etcd/consul等中间件watch下发配置
- 定期去一个集中化平台来拉取? 比如有一个配套的manager平台?

有类似需求,  在考虑方案.

**Comment by taoyuanyuan** [comment]
这块就是根据大家的实际诉求来，欢迎pr 👏

**Comment by Jun10ng** [comment]
可以把获取配置的功能做成插件模式。
初始化的时候可以选择自己选择/实现插件，比如从aollo获取或者自己公司的配置中心轮子上获取。

做过类似的需求，可惜最后没上线，因为基础架构部门的人也做了相同的功能，最后决定使用他们提供的 T T

**Comment by taoyuanyuan** [comment]
> 做过类似的需求，可惜最后没上线，因为基础架构部门的人也做了相同的功能，最后决定使用他们提供的 T T

那可以贡献给社区 😄

**Comment by Jun10ng** [comment]
Follow here https://github.com/mosn/holmes/issues/48
