### ISSUE TITLE
有没有朋友遇到过这个问题

### ISSUE THREAD

**Issue by x-wesley** [mosn/holmes#22]
类似这个 https://github.com/golang/go/issues/40974

goland里面执行gotest没有问题。

项目里go install 命令的时候出现以下问题：
/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: sectionForAddress(0x13654DE) address not in any section file '/var/folders/rr/2rdmy50d1jb0tjnjfhcbnbqh0000gn/T/go-link-273425566/go.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

升级go版本至1.15.5后问题消失

**Comment by cch123** [comment]
汗，还以为是 holmes 的问题
这个应该是混编了不同版本的依赖吧
试试把 go mod cache clean 掉

**Comment by x-wesley** [comment]
> 汗，还以为是 holmes 的问题
> 这个应该是混编了不同版本的依赖吧
> 试试把 go mod cache clean 掉

没有用gomod  还是vendor呢

**Comment by nejisama** [comment]
试下把GCO禁掉跑跑看呢？ CGO_ENABLED=0
