### ISSUE TITLE
句柄打满监控

### ISSUE THREAD

**Issue by xiezhenouc** [mosn/holmes#24]
最近遇到流量比较大的模块，可能会出现too many files句柄打满错误。其中一个原因是物理机句柄限制。另外一个，由于是偶现，抓不到现场，现在还不知道原因。。所以这个工具是否可以帮助我们抓到这个现场，定位到具体的问题。

**Comment by cch123** [comment]
简单的思路似乎是可以先采集 fd 数：
https://stackoverflow.com/questions/21752067/counting-open-files-per-process

然后当 fd 数异常飚升时，用 lsof -p pid 把信息采集下来

不过感觉这个采集 fd 数成本好像有点高啊。。

**Comment by xiezhenouc** [comment]
"不过感觉这个采集 fd 数成本好像有点高啊。。"

对，我们线上有高并发模块，物理机部署，采集 fd 数 挺慢的。。

**Comment by taoyuanyuan** [comment]
@xiezhenouc 看你描述是大流量，如果是连接数的socket句柄导致的，通过goroutine的dump是可以抓到现场的。

**Comment by xiezhenouc** [comment]
嗯，感谢大佬~

**Comment by xiezhenouc** [comment]
> @xiezhenouc 看你描述是大流量，如果是连接数的socket句柄导致的，通过goroutine的dump是可以抓到现场的。
