### ISSUE TITLE
getUsage 为什么要区分为normal常见和cgroup？

### ISSUE THREAD

**Issue by Jun10ng** [mosn/holmes#34]
我看到cgroup场景下的getUsage方法复杂了很多，请问是有什么考量吗。

**Comment by cch123** [comment]
> 我看到cgroup场景下的getUsage方法复杂了很多，请问是有什么考量吗。

容器里要按照系统给当前实例分配的内存和 CPU 核数来计算百分比，

这样稍微准一些，用宿主机的肯定不行
