### ISSUE TITLE
Why CPU Dump didn't work

### ISSUE THREAD

**Issue by Jun10ng** [mosn/holmes#41]
I run holmes inside my application and set the follow options.
```
       // other initial


	h, _ := holmes.New(
		holmes.WithCollectInterval("5s"),
		holmes.WithCoolDown("1m"),
		holmes.WithDumpPath("/tmp"),
		holmes.WithCPUDump(1, 25, 80),
		holmes.WithCPUMax(90),
	)
	h.EnableCPUDump()

	// start the metrics collect and dump loop
	h.Start()

      // server start

```

then I run a eating cpu shell script, and the following screenshot is `top` command output, CPU usage rate is almost 100%.
![image](https://user-images.githubusercontent.com/46768176/149647115-a69c4b04-db32-48ba-acdb-7f5e3b6c20ef.png)

but I check `holmes.log` it shows CPU usage rate is 0%

![image](https://user-images.githubusercontent.com/46768176/149647222-988a479b-5719-40d2-a3d7-999ad9686a6d.png)

**Comment by Jun10ng** [comment]
Maybe holmes is only sensitive to the resource taken by my applicant?  
Not of all programs running on server.

**Comment by Jun10ng** [comment]
the example at cpu_explode also does work, after warming up, I try to curl /cpuex 10 times, holmes record CPU usage always 0, I run this example at my mac(go version 1.14) and linux server.(go version 1.12)

**Comment by cch123** [comment]
holmes only get cpu percent used by the app

**Comment by Jun10ng** [comment]
thanks, I close this issue
