### ISSUE TITLE
A discussion about dynamic configuration.

### ISSUE THREAD

**Issue by Jun10ng** [mosn/holmes#48]
Hi team,

I saw there was [an issue](https://github.com/mosn/holmes/issues/2) about "dynamic configuration", and I want to discuss some questions about it.

1. The definition of "dynamic" is holmes pull/receive configurations from a remote server? or holmes can adjust its configuration automatically through pre-prepared plans？
2. If its definition is the former, holmes receive configuration from Apollo/Redis/API or some service built by users themselves, we better **draft an abstract API**, and implement dynamic config feature based on the API. 
3. Does we support hot-load configuration? I mean weather holmes supports modifying its config when it is running? Or just on a simple way-- only load configuration from remote when holmes is initiating. The change to support the former seems great.

**Comment by cch123** [comment]
dynamic means config hot reload
holmes supports reconfig without restart inside ant's internal usage, but ant's config management system is not a common one, open-source version of holmes needs to support various config store:  etcd, apollo, etc.
if you're using it in a few instances, config hot reload is not a pain point, if it's used in big scale of instances like more than 100k instances, you'll need this feature.

**Comment by doujiang24** [comment]
I think the first step is to expose a dynamic `Set` method, similar to the `New` method.
The important thing is that we should make it atomic during a single `xxxCheckAndDump`.

**Comment by Jun10ng** [comment]
Set API has developed.

If user wants to support dynamic configuration, just compatible their config listen method and holmes Set API.


Close it.
