### ISSUE TITLE
add license and release for prod

### ISSUE THREAD

**Issue by cch123** [mosn/holmes#55]
Some users want to use holmes on their production env and hesitate for the license and beta ver, currently most features of holmes have already been stable enough

v1 should be soon released, 

another question is what license should this lib be? @nejisama @doujiang24 @taoyuanyuan 
apache v2?

**Comment by doujiang24** [comment]
Apache v2.0 is good enough, just align with MOSN.

**Comment by cch123** [comment]
https://github.com/mosn/holmes/releases/tag/v1.0.0
