### ISSUE TITLE
feature: support external logger.

### ISSUE THREAD

**Issue by doujiang24** [mosn/holmes#59]
we create logger based on the file in holmes, it makes holmes easier to use standalone.
but sometimes, we already have logger, we'd better support just use the existing logger instead create a new one.
it will make holmes easier to integrate.

**Comment by Jun10ng** [comment]
could you assign it to me? tks

**Comment by songzhibin97** [comment]
abstract into an interface?

**Comment by doujiang24** [comment]
> abstract into an interface?

@songzhibin97 yeah, holmes define an interface and accept an external interface value.

**Comment by Jun10ng** [comment]
hi @songzhibin97 Could I assign this issue for u, cuz I found the logger module has a lot of options is created by u, and I no sure what they are mean, and I  can take charge of another issue https://github.com/mosn/holmes/issues/58. 

lol, I think this is more effective and it's up to you.

**Comment by songzhibin97** [comment]
sure
