### ISSUE TITLE
example Dump事件上报 拼写错误

### ISSUE THREAD

**Issue by lyjgk** [mosn/holmes#88]
type ReporterImpl struct{}
        func (r *ReporterImple) Report(pType string, buf []byte, reason string, eventID string) error{
            // do something	
        }

ReporterImple && ReporterImpl

**Comment by doujiang24** [comment]
@lyjgk Thanks, patches are welcome!

**Comment by Jun10ng** [comment]
follow into https://github.com/mosn/holmes/pull/91
