### ISSUE TITLE
Support Dump Goroutines to logger

### ISSUE THREAD

**Issue by zhangqibupt** [mosn/holmes#90]
Currently, the goroutines are dumped into specified file path, sometimes it might be hard for us to check. 
Is it possible to support to dump goroutines to logger? If so we can see check it in our existing log system(ELK). Thanks.

**Comment by Jun10ng** [comment]
follow into https://github.com/mosn/holmes/pull/91

**Comment by christianmoss4824dennismartinez** [comment]
Thank you so much for the great effort!

**Comment by zhangqibupt** [comment]
Thank you guys, you are the best.
