### ISSUE TITLE
reporter interface: used filename instead of byte slice

### ISSUE THREAD

**Issue by doujiang24** [mosn/holmes#96]
`filename` is more flexible, people can read bytes from the file, or just report the filename.

it's a breaking change, but I think it's worthing.

**Comment by doujiang24** [comment]
related code: https://github.com/mosn/holmes/blob/master/holmes.go#L75

**Comment by songzhibin97** [comment]
Modify the interface or add a parameter, is that what you mean?

**Comment by doujiang24** [comment]
@songzhibin97 I think changing the current interface is better.
